services:
  #*********** PROXY ***********
  mvp-proxy:
    image: nginx:1.23.3-alpine
    container_name: mvp-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - ./mvp-db.conf:/etc/nginx/conf.d/mvp-db.conf
      - ./mvp-paymybuddy.conf:/etc/nginx/conf.d/mvp-paymybuddy.conf
    networks:
      - applications-network

  #*********** NETWORK ***********
networks:
  applications-network:
    driver: bridge