name: deploy back
on: [ push ]
env:
    IMAGE: proxy
    VERSION: 0.0.1
jobs:
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
    steps:
      - name: execute commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            mkdir /opt/applications/mvp_projets/${{env.IMAGE}}
            ls -al /opt/applications/mvp_projets

  run-container:
    name: run-container
    runs-on: ubuntu-latest
    needs: ['create-folder']
    steps:
      - name: Clone sources with checkout
        uses: actions/checkout@v4

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml, mvp-db.comf, mvp-paymybuddy.conf"
          target: /opt/applications/mvp_projets/${{env.IMAGE}}

      - name: execute commands to run container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            docker compose -f /opt/applications/mvp_projets/${{env.IMAGE}}/docker-compose.yml up -d

